version: '3'

services:

  payment:
    image: $IMAGE_NAME
    container_name: $CONTAINER_NAME
    ports: 
      - 8089:8089
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0.19
    container_name: mysql-container
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/jc/database/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306

networks:
  default:
    external:
      name: cluster-network